package edu.training.web.controller.concrete;

public enum CommandName {
	DO_AUTH, DO_REGISTRATION, DO_LOGOUT, DO_EDIT,

	ADD_NEWS, EDIT_NEWS,

	GO_TO_INDEX_PAGE, GO_TO_MAIN_PAGE, GO_TO_REGISTRATION_PAGE, GO_TO_SIGN_IN_PAGE,

	GO_TO_ADDING_NEWS_PAGE,

	SHOW_THE_WEATHER, SHOW_GOOD_NEWS, SHOW_BUSINESS_NEWS, SHOW_LIVE_NEWS, SHOW_POLITICAL_NEWS, SHOW_SPORT_NEWS,

	NO_SUCH_COMMAND, LOCALIZATIONS
}
